### ISSUE TITLE
CSS bug in Firefox

### ISSUE THREAD

**Issue by YuriySm** [dav3860/zabbix_dashboard#1]
Hi! Nice job you have done, tnx! ;)

I found a little visual bug in Firefox (v. 33.0, Ubuntu). When the widget square should have a  special status color it still remain in default green color.

The CSS style is always overrided by inline (green) style in Firefox. Chrome has no such problem and the colors are fine there.

![](http://sel.i2.5cm.ru/i/QnWv.png)

**Comment by dav3860** [comment]
Thanks for reporting. I will have a look at it.
