### ISSUE TITLE
Hostnames

### ISSUE THREAD

**Issue by Nosaj123** [dav3860/zabbix_dashboard#4]
Thanks for this, implemented this in RHEL 7.

But is there anyway I can add the Hostname on the widgets?

As it stands the triggers are displayed, but doesn't show which Host it is associated with.

**Comment by dav3860** [comment]
Hi,
The hostnames should be displayed as well in the widgets. Do you mean the list widget or the severity widgets on the left ?

**Comment by Nosaj123** [comment]
Hi, 
I am not seeing the hostnames listed, just the Host Group title which I've set in the config file? You can see a sample SS of my setup 
![screen shot 2016-03-07 at 10 45 53 pm](https://cloud.githubusercontent.com/assets/5449080/13591481/0581b93c-e4b7-11e5-8305-5781549d1c08.png)

**Comment by dav3860** [comment]
It should appear. Can you check the javascript console in Chrome Developper Tools for example. Look at the "_list" objects. If you expand the object, does it contains a "host" property ?

**Comment by dav3860** [comment]
I've updated the code to work with Zabbix 3.0.
