### ISSUE TITLE
undefined method gsub' for nil:NilClass

### ISSUE THREAD

**Issue by lucafeudi** [dav3860/zabbix_dashboard#5]
Thank you for sharing this. 
I'm having some problem getting Events from Zabbix Server:
![dashboard error](https://cloud.githubusercontent.com/assets/4534778/13666294/116c6336-e6b1-11e5-973c-aab68efc8070.jpg)

I think login is successful.
I will attach history.yml , hoping it will be useful to track the issue:

```
cat history.yml 

---
Production_text: ! 'data: {"title":"DASHBOARD IN ERROR : undefined method `gsub''
  for nil:NilClass","status":"disa-blink","id":"Production_text","updatedAt":1457602562}


'
Development_text: ! 'data: {"title":"DASHBOARD IN ERROR : undefined method `gsub''
  for nil:NilClass","status":"disa-blink","id":"Development_text","updatedAt":1457602562}
```

I will give you some more information about enviroment:
SO: Ubuntu 14.04
Zabbix: 3.0

I look forward to hearing from you soon

**Comment by dav3860** [comment]
gsub is used on the hostname field of the triggers. You can comment line 104 of zabbix.rb to confirm this. But the trigger objects should contain a hostname. What version of Zabbix do you have ?

**Comment by lucafeudi** [comment]
I'm using Zabbix 3.0

**Comment by Nosaj123** [comment]
Hey Lucafeudi, to resolve your issue you need to edit the zabbix.rb file which is located in the jobs folder.
In line 105, replace the code with  hostnme = **_hostnme.to_s.gsub_**(/..*$/, '') # strip domain name if necessary

**Comment by lucafeudi** [comment]
It work like a charm, thank you.
