### ISSUE TITLE
zabbix dasboard for dashing

### ISSUE THREAD

**Issue by Ronaldschouw** [dav3860/zabbix_dashboard#6]
Hi,
Just upgrade to zabbix 3,0
Find out that our dashboard fails on the API.
ZABBY::APIError.
It seems that get "expandData" is deprecated and removed from zabbix 3.0
ZBXNEXT-2724 application.get: removed the deprecated “expandData” parameter 
 # Query Zabbix for current problem triggers
      result = serv.run {
      Zabby::Trigger.get(
        "filter" => {"value" => 1 },
        "min_severity" => MINPRIORITY,
        "groupids" => groupids,
        "output" => "extend",
        "monitored" => 1,
        "withLastEventUnacknowledged" => 1,
        "skipDependent" => 1,
        "expandData" => "host",
        "expandDescription" => 1,
        "sortfield" => "lastchange",
        "sortorder" => "DESC")
      }

Can you fix this issue,
Any help is welcome,

Regards.
Ronald Schouw

**Comment by Emusp** [comment]
We have the same problem. Updated to Zabbix 3.0. 

Would really be nice if we could get the code updated, so it works with the new API.
Maybe it's also because it using the Zabby gem. It's not ben updated in 4 years.

**Comment by dav3860** [comment]
I've updated the code to work with Zabbix 3.0.
